---

- name: ping marathon consul to check if it is ready
  shell: "curl --silent -k -u {{marathon_username}}:{{marathon_password}} {{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/ping"
  register: result_ping
  until: result_ping.stdout.find("pong") != -1
  retries: 20
  delay: 30


- name: start VIRGO worker nodes
  run_once: true
  uri:
    url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/condorwn?force=true"
    force_basic_auth: yes
    user: "{{marathon_username}}"
    password: "{{marathon_password}}"
    validate_certs: no
    method: PUT
    headers:
      Content-Type: "application/json"
    # Template has privileged because it can have access to host devices
    # and it is in BRIDGE mode to have different hostname for
    # condor nodes, otherwise they can't be recognized by master
    body: "{{ lookup('template', 'templates/condor_wn.json') }}"
    body_format: json
    status_code: [200, 201, 409]  # app created, deployment started, already running deployment
    return_content: yes
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - virgo_apps


- name: start VIRGO cvmfs check
  run_once: true
  uri: 
     url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/cvmfscheck"
     user: "{{marathon_username}}"
     password: "{{marathon_password}}"
     validate_certs: "no"
     method: PUT
     HEADER_Content-Type: "application/json"
     body: "{{ lookup('template', 'templates/cvmfskeepalive.json') }}"
     body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false
  tags:
    - virgo_apps
